# Secret for PostgreSQL sensitive configuration
# This is a template - actual values will be populated by the migration script
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: hackystack
  labels:
    app: postgresql
    component: secrets
type: Opaque
data:
  # PostgreSQL superuser password (base64 encoded)
  # This will be populated by the migration script
  POSTGRES_PASSWORD: ""
  
  # PostgreSQL database name (base64 encoded)
  POSTGRES_DB: "aGFja3lzdGFjaw=="  # hackystack
  
  # PostgreSQL application user (base64 encoded)
  POSTGRES_USER: "aGFja3lzdGFjaw=="  # hackystack
  
  # PostgreSQL application user password (base64 encoded)
  # This will be populated by the migration script
  POSTGRES_APP_PASSWORD: ""
  
  # Complete database URL for the application (base64 encoded)
  # This will be populated by the migration script in format:
  # postgresql://hackystack:password@postgresql-service:5432/hackystack
  DATABASE_URL: ""