apiVersion: v1
kind: Service
metadata:
  name: hackystack-service
  labels:
    app: hackystack
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: hackystack

---
apiVersion: v1
kind: Service
metadata:
  name: hackystack-headless
  labels:
    app: hackystack
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: hackystack