# Secret for sensitive configuration
# This is a template - actual values will be created by the deployment script
# All values must be base64 encoded
apiVersion: v1
kind: Secret
metadata:
  name: hackystack-secrets
  namespace: hackystack
  labels:
    app: hackystack
    component: secrets
type: Opaque
data:
  # NextAuth.js secret for session encryption
  # This will be populated by the deployment script
  NEXTAUTH_SECRET: ""
  
  # GitHub OAuth credentials
  # These will be populated by the deployment script during deployment
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  
  # Database connection URL for external PostgreSQL
  # This will be populated by the deployment script
  DATABASE_URL: ""